{"author":{"id":"4a66333145a8be3a1fab83bfb67acb16b49eec9bba93a1d3ada9ca43625279f7"},"ops":[{"type":3,"author":{"id":"4a66333145a8be3a1fab83bfb67acb16b49eec9bba93a1d3ada9ca43625279f7"},"timestamp":1565020995,"nonce":"U3hjX0nF5PCLGKHjUJiVkdeiKpE=","message":"Jah, ennyi az ötlet, u.úgy elkapni az exceptiont mint ahogy a webappnál már meg van oldva.","files":null},{"type":3,"author":{"id":"4a66333145a8be3a1fab83bfb67acb16b49eec9bba93a1d3ada9ca43625279f7"},"timestamp":1565106902,"nonce":"Y4bIHTs+1q5IxcIMqPyVW+bdSWw=","message":"Ma amúgy megint lefutott gond nélkül. De minden esetre a fenti most már logol mindent, így legközelebb ha ez előjön, okosabbak leszünk.","files":null},{"type":4,"author":{"id":"4a66333145a8be3a1fab83bfb67acb16b49eec9bba93a1d3ada9ca43625279f7"},"timestamp":1565106902,"nonce":"AEQhl+LIunlG8nH9YkXYTDhTovc=","status":2}]}