{"author":{"id":"d6f72f3bb7fe53f0c6a700e6cdbc1293cabf7ce3cfccf3c323291f67735a1015"},"ops":[{"type":1,"author":{"id":"d6f72f3bb7fe53f0c6a700e6cdbc1293cabf7ce3cfccf3c323291f67735a1015"},"timestamp":1615763478,"nonce":"wkpqmlxzCeLoG6FCrGLwkSNghtI=","title":"invalid-relations ha még nincs legenerálva egy terület, akkor hibára fut","message":"Ha akarjuk kezelni. Újonnan hozzáadott területnél, ha még nincs referencia, akkor az alábbi errort dobja:\n\n```\nBelső hiba a /osm/housenumber-stats/hungary/invalid-relations kiszolgálása során\nTraceback (most recent call last):\n  File \"/home/osm-gimmisn/git/osm-gimmisn/wsgi.py\", line 943, in application\n    return our_application(environ, start_response)\n  File \"/home/osm-gimmisn/git/osm-gimmisn/wsgi.py\", line 928, in our_application\n    doc.asis(handler(relations, request_uri).getvalue())\n  File \"/home/osm-gimmisn/git/osm-gimmisn/webframe.py\", line 380, in handle_stats\n    return handle_invalid_refstreets(relations)\n  File \"/home/osm-gimmisn/git/osm-gimmisn/webframe.py\", line 358, in handle_invalid_refstreets\n    invalid_refstreets = areas.get_invalid_refstreets(relation)\n  File \"/home/osm-gimmisn/git/osm-gimmisn/areas.py\", line 681, in get_invalid_refstreets\n    osm_streets = [i.get_osm_name() for i in relation.get_osm_streets()]\n  File \"/home/osm-gimmisn/git/osm-gimmisn/areas.py\", line 354, in get_osm_streets\n    with self.get_files().get_osm_streets_csv_stream() as sock:\n  File \"/home/osm-gimmisn/git/osm-gimmisn/areas.py\", line 53, in get_osm_streets_csv_stream\n    return util.CsvIO(self.__get_osm_streets_stream(\"r\"))\n  File \"/home/osm-gimmisn/git/osm-gimmisn/areas.py\", line 49, in __get_osm_streets_stream\n    return cast(TextIO, open(path, mode=mode))\nFileNotFoundError: [Errno 2] No such file or directory: '/home/osm-gimmisn/git/osm-gimmisn/workdir/streets-istvantelek.csv'\n```","files":null},{"type":6,"author":{"id":"d6f72f3bb7fe53f0c6a700e6cdbc1293cabf7ce3cfccf3c323291f67735a1015"},"timestamp":1615763528,"nonce":"HQDk2PagllYQRP0wK942zFJeCbw=","target":"47d8d22afb0de449e443299bd627a32d0fc9d5f22cac580ecbfa824cd16f3461","message":"Ha akarjuk kezelni. Újonnan hozzáadott területnél, ha még nincs referencia, akkor az alábbi errort dobja:\n(szerintem egyszerűen ki kellene hagynia azt amit nem talál)\n\n```\nBelső hiba a /osm/housenumber-stats/hungary/invalid-relations kiszolgálása során\nTraceback (most recent call last):\n  File \"/home/osm-gimmisn/git/osm-gimmisn/wsgi.py\", line 943, in application\n    return our_application(environ, start_response)\n  File \"/home/osm-gimmisn/git/osm-gimmisn/wsgi.py\", line 928, in our_application\n    doc.asis(handler(relations, request_uri).getvalue())\n  File \"/home/osm-gimmisn/git/osm-gimmisn/webframe.py\", line 380, in handle_stats\n    return handle_invalid_refstreets(relations)\n  File \"/home/osm-gimmisn/git/osm-gimmisn/webframe.py\", line 358, in handle_invalid_refstreets\n    invalid_refstreets = areas.get_invalid_refstreets(relation)\n  File \"/home/osm-gimmisn/git/osm-gimmisn/areas.py\", line 681, in get_invalid_refstreets\n    osm_streets = [i.get_osm_name() for i in relation.get_osm_streets()]\n  File \"/home/osm-gimmisn/git/osm-gimmisn/areas.py\", line 354, in get_osm_streets\n    with self.get_files().get_osm_streets_csv_stream() as sock:\n  File \"/home/osm-gimmisn/git/osm-gimmisn/areas.py\", line 53, in get_osm_streets_csv_stream\n    return util.CsvIO(self.__get_osm_streets_stream(\"r\"))\n  File \"/home/osm-gimmisn/git/osm-gimmisn/areas.py\", line 49, in __get_osm_streets_stream\n    return cast(TextIO, open(path, mode=mode))\nFileNotFoundError: [Errno 2] No such file or directory: '/home/osm-gimmisn/git/osm-gimmisn/workdir/streets-istvantelek.csv'\n```","files":null},{"type":5,"author":{"id":"d6f72f3bb7fe53f0c6a700e6cdbc1293cabf7ce3cfccf3c323291f67735a1015"},"timestamp":1615763484,"nonce":"vBAl64ZK0zVsaatSO96ub8OLYLM=","added":["bug"],"removed":null}]}