{"version":2,"ops":[{"type":1,"author":{"id":"653ad5a5221de41f1bb6e2b766642806e048c3d8"},"timestamp":1582315342,"metadata":{"github-id":"MDU6SXNzdWU1NjkxNTcyMDE=","github-url":"https://github.com/vmiklos/osm-gimmisn/issues/336","origin":"github"},"title":"Új terület: meglévő házszám linkre error-t dob","message":"Ha még nincs legenerálva a meglévő házszám, error jön. \n\nReprodukció\n1) Új terület hozzáadása, relations-ben\n2) Meglévő házszámok-ra kattintás\n\nEz jön:\nBelső hiba a /osm/street-housenumbers/budaors-kamaraerdo/view-result kiszolgálása során\nTraceback (most recent call last):\n  File \"/home/vmiklos/git/osm-gimmisn/wsgi.py\", line 774, in application\n    return our_application(environ, start_response)\n  File \"/home/vmiklos/git/osm-gimmisn/wsgi.py\", line 759, in our_application\n    doc.asis(handler(relations, request_uri).getvalue())\n  File \"/home/vmiklos/git/osm-gimmisn/wsgi.py\", line 105, in handle_street_housenumbers\n    with relation.get_files().get_osm_housenumbers_stream(mode=\"r\") as sock:\n  File \"/home/vmiklos/git/osm-gimmisn/areas.py\", line 62, in get_osm_housenumbers_stream\n    return cast(TextIO, open(path, mode=mode))\nFileNotFoundError: [Errno 2] No such file or directory: '/home/vmiklos/git/osm-gimmisn/workdir/street-","files":null}]}